Done implement main screen, improve splash screen
simplesoft-duongdt3/CoffeeAppKotlinHacking pull request #1
Opened 2019-01-06 06:19 UTC by HuynhXinh

2019-01-10 10:17 UTC, simplesoft-duongdt3 commented on .idea/assetWizardSettings.xml
>                          <option name="values">
ignore .idea folder

2019-01-10 10:18 UTC, simplesoft-duongdt3 commented on app/build.gradle
> +    implementation presentationDependencies.butterknife
using Kotlin Synthetic Binding instead of butter knife

2019-01-10 10:21 UTC, simplesoft-duongdt3 commented on app/src/main/java/com/coffeetek/todo/feature/main/bottommaintab/BottomMainTabState.kt
> +            setNormalStyle(iView.getTabHome())
ignore use enum for change UI, best practice is using enum as state

2019-01-10 10:22 UTC, simplesoft-duongdt3 commented on app/src/main/java/com/coffeetek/todo/feature/main/bottommaintab/BottomMainTabView.kt
> +        bottomMainTabState.updateUi(this)
move logic into presenter

2019-01-10 10:35 UTC, simplesoft-duongdt3 commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/fl_activity_main_content"
Follow flActitivyMainContent naming convention

2019-01-10 10:36 UTC, simplesoft-duongdt3 requested changes
Please read my review comments

2019-01-10 10:39 UTC, simplesoft-duongdt3 approved these changes

2019-01-10 10:41 UTC, simplesoft-duongdt3 requested changes
Read my review comments

2019-01-11 06:22 UTC, HuynhXinh commented on app/build.gradle
> +    implementation presentationDependencies.butterknife
Can you make an example :)

2019-01-11 06:25 UTC, HuynhXinh commented on app/src/main/java/com/coffeetek/todo/feature/main/bottommaintab/BottomMainTabState.kt
> +            setNormalStyle(iView.getTabHome())
Yes, you are right.
But my purpose want to use state pattern
Refer: http://www.codinginsights.blog/design-patterns-state/
And I also see duplicate set listener, need to improve

2019-01-11 06:29 UTC, HuynhXinh commented on app/src/main/java/com/coffeetek/todo/feature/main/bottommaintab/BottomMainTabView.kt
> +        bottomMainTabState.updateUi(this)
It no logic, just update UI :) and purpose is just custom view
I want to split small view to easy handle and public call back
And once more things presenter is no supper class, bester use for handle business logic not related custom view

2019-01-11 06:48 UTC, simplesoft-duongdt3 commented on app/build.gradle
> +    implementation presentationDependencies.butterknife
https://medium.com/coding-blocks/goodbye-findviewbyid-say-hello-to-synthetic-binding-in-kotlin-d3727bd8438e

2019-01-11 08:17 UTC, simplesoft-duongdt3 approved these changes

2019-01-11 08:17 UTC, merged